name: nyxx_commands
version: 4.0.0-dev.2.0
description: A framework for easily creating slash commands and text commands for Discord using the nyxx library.

homepage: https://github.com/nyxx-discord/nyxx_commands/blob/main/README.md
repository: https://github.com/nyxx-discord/nyxx_commands
issue_tracker: https://github.com/nyxx-discord/nyxx_commands/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  meta: ^1.7.0
  nyxx: ^3.0.0
  nyxx_interactions: ^4.0.0-dev.0.1
  random_string: ^2.3.1

dev_dependencies:
  build_runner: ^2.1.4
  coverage: ^1.0.3
  lints: ^1.0.1
  mockito: ^5.0.16
  test: ^1.19.0
