name: nyxx_commands
version: 3.1.1
description: A framework for easily creating slash commands and text commands for Discord using the nyxx library.

homepage: https://github.com/nyxx-discord/nyxx_commands/blob/main/README.md
repository: https://github.com/nyxx-discord/nyxx_commands
issue_tracker: https://github.com/nyxx-discord/nyxx_commands/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  meta: ^1.7.0
  nyxx: ^3.0.0
  nyxx_interactions: ^3.1.0

dev_dependencies:
  test: ^1.19.0
  mockito: ^5.0.16
  build_runner: ^2.1.4
  lints: ^1.0.1
  coverage: ^1.0.3
